### ISSUE TITLE
function Base.getindex(out::FMU2EvaluationOutput, ind) is not prepared when ind is a vector of indices

### ISSUE THREAD

**Issue by juguma** [ThummeTo/FMICore.jl#56]
Base.getindex is called when the input arguments are an FMU2EvaluationOutput (out) and anything but not a CartesianIndex{A}.
In the example below, ind is a vector of indices.

Minimal example
```
import FMI: Base.getindex
fmi = fmiLoad("SpringPendulumExtForce1D", "Dymola", "2022x"; type=:ME)
fmiSimulate(fmi) #<-since no FMU2Component allocated <-and I will make a ticket rightaway for that.
Base.getindex(fmu(;dx_refs=:all),[1,2])
```

You need this when you want to make a Flux.Chain which uses a substet of the FMU-derivatives, e.g.
```
inputN = [2,9,10,12,17,24,25]
net = Chain(x -> myFMU(; x=x,dx_refs=:all),
            dx -> cache(dx),                     
            dx -> dx[inputN],
		…)
```
There is a workaround (if you only have dx-Output): One can use `myFMU(...).dx` as output of the first layer.

Proposed solution!?
Dispatch for `ind::AbstractVector{<:Integer}`
If that's okay for you, I can make a draft.

**Comment by ThummeTo** [comment]
Yep, you are correct. See #58
